services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      MONGO_URI: mongodb://mongo:27017/taskdb
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017'
